services:
  kickmcsr:
    build:
      context: .
    image: kickmcsr-bot:latest
    container_name: kickmcsr
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
